# version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  cpp_app:
    build:
      context: ./student_code
      dockerfile: Dockerfile-1
    container_name: cpp_app_container
    volumes:
      - ./student_code:/usr/src/student_code
    environment:
      DATABASE_HOST: localhost
    extra_hosts:
      - "localhost:172.20.0.2"
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16