CREATE TABLE IF NOT EXISTS user_info (
    userid BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    deviceid VARCHAR(36) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_data (
    userid BIGINT PRIMARY KEY,
    data VARCHAR(256) NOT NULL
);