FROM gcc:13
RUN apt-get update && apt-get install -y cmake git build-essential
WORKDIR /usr/src/student_code
ENV BUILD_DIR=build

# first. set postgres information env
# ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=postgres
# ENV POSTGRES_DB=postgres
# ENV POSTGRES_HOST=localhost
# ENV POSTGRES_PORT=5432
ENV DATABASE_INFO="dbname=postgres user=postgres password=postgres hostaddr=172.20.0.2 port=5432"

# second, set max thread pool size
ENV THREAD_POOL_SIZE=2

# third, install dependencies
RUN apt-get install -y libpq-dev rapidjson-dev

# last, build and start server!
# CMD ["sh", "-c", "while true; do sleep 1000; done"]
CMD ["sh", "-c", \
    "if [ -d \"$BUILD_DIR\" ]; then \
        rm -rf $BUILD_DIR; \
    fi && \
    mkdir $BUILD_DIR && \
    cd $BUILD_DIR && \
    cmake .. && \
    make -j `nproc` && \
    cd ../bin && \
    ./server 8888 ../html"]

