FROM gcc:13
RUN apt-get update && apt-get install -y cmake git build-essential
WORKDIR /usr/src/student_code
ENV BUILD_DIR=build

# first. set postgres information env
ENV SERVER_POSTGRES_USER=postgres
ENV SERVER_POSTGRES_PASSWORD=postgres
ENV SERVER_POSTGRES_DB=postgres
ENV SERVER_POSTGRES_HOST=localhost
ENV SERVER_POSTGRES_PORT=5432

# second, set max thread pool size
ENV THREAD_POOL_SIZE=2

# third, install dependencies
RUN apt-get install -y libpqxx-dev rapidjson-dev

# last, build and start server!
# CMD ["sh", "-c", "while true; do sleep 1000; done"]
CMD ["sh", "-c", \
    "if [ -d \"$BUILD_DIR\" ]; then \
        rm -rf $BUILD_DIR; \
    fi && \
    mkdir $BUILD_DIR && \
    cd $BUILD_DIR && \
    cmake .. && \
    make -j `nproc` && \
    cd ../bin && \
    ./server 8888 ../html"]

